/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 52c2cabfe9ec7a340c845e6d63f41913)
interface __BaseEnv_Env {
	ASSET_BUCKET: R2Bucket;
	BACKUP_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	NODE_ENV: "production";
	AUTH_MODE: "access";
	CONTENT_SOURCE: "bundled";
	CLOUDFLARE_ACCOUNT_ID: "f14987cb2f1db42ebfde241a23700328";
	BACKUP_BUCKET_NAME: "miriad-staging-checkpoints";
	SPACES: DurableObjectNamespace<import("./src/index").SpaceAgent>;
	SANDBOX: DurableObjectNamespace<import("./src/index").Sandbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SpaceAgent" | "Sandbox";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "AUTH_MODE" | "CONTENT_SOURCE" | "CLOUDFLARE_ACCOUNT_ID" | "BACKUP_BUCKET_NAME">> {}
}
